### PR TITLE
[WIP] Configuration branching

### PR DESCRIPTION
**Pull request by DatCorno**

### CODE REVIEW

**Comment by bouthilx** [comment]
@DatCorno Can you rebase on feature/evc and drop commits prior to 639b71f63fdf4c06ba046fff58dd0be4bb78af62 (don't drop 639b71f63fdf4c06ba046fff58dd0be4bb78af62 itself, but those before it!). 

I would recommend you to do the rebase in a new branch just in case everything breaks. :)

**Comment by DatCorno** [comment]
Rebase has been done, this PR is missing the config file portion of the solving process and doc/pylint/flake8 issues.

**Comment by bouthilx** [comment]
What? doc/pylint/flake8 are not fixed on the fly? :stuck_out_tongue_closed_eyes:

**Comment by DatCorno** [comment]
Not when you forget to do your docstrings :grimacing:

**Pull request closed without merging**
