### PR TITLE
Feature: Add transformations of points, Dimension, Space, and a builder for that

### PR DESCRIPTION
**Pull request by tsirif**
Also, implement them in PrimaryAlgo whose responsibility is exactly that.

Currently, this PR is not complete.

Missing:
- [x] Actual implementations of Transform classes :stuck_out_tongue: 
- [x] Unittests
- [x] Some documentation of some methods

### CODE REVIEW

**Comment by bouthilx** [comment]
@tsirif Is this one ready for review?

**Comment by tsirif** [comment]
@bouthilx I am pushing tests and it is!

**Comment by bouthilx** [comment]
I looked at it quickly. It looks good in general but there is 2-3 spots I'd like to look at more in details. Because the deadline is close I will push some more work on the EVC and then I'll look at this PR tomorrow.

**Comment by bouthilx** [comment]
@tsirif Ping :)

**Pull request merged**
